name: ui_effects
description: "Create ui side effects from anywhere in your code"
version: 2.0.0
homepage: https://github.com/Yoeri-z/ui_effects
repository: https://github.com/Yoeri-z/ui_effects
issue_tracker: https://github.com/Yoeri-z/ui_effects/issues

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  show_toast: ^0.1.0
  async: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
